### ISSUE TITLE
Debain package 1.0.3 error

### ISSUE THREAD

**Issue by heptahex** [Gnurou/tagainijisho#248] opened 2021-12-16 08:28 UTC
I've installed Tagaini from Debian package and installed all dependencies but it seems some plugins have error. Although tagaini (AUR) worked well on my Manjaro Linux. This happened on Pop OS 20.04.

![tagaini-report](https://user-images.githubusercontent.com/82636866/146335345-11b3718f-8237-471b-a18e-8a8231538881.png)

**Comment by Gnurou** [comment] 2022-01-15 07:25
Sorry for the delayed reply. Where did you get the debian package, or in case you created it yourself, how have you built it?

**Comment by Gnurou** [comment] 2022-01-16 02:48
Found that you were probably referring to the packages on the release page. I have been able to reproduce and am looking for the cause.

**Comment by Gnurou** [comment] 2022-01-16 02:55
For some reason `cpack` installs the databases in `/usr/share` despite the default build looking for them in `/usr/local/share`. The simplest fix is the specify the expected prefix when building the program for packaging, i.e.

```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/ .
$ cpack -G DEB
```

The produced `.deb` file then works without issue. I'll close this, please expect working packages from now on. Thanks for reporting!

**Closed by Gnurou** 2022-01-16 02:55 UTC
